-- Migration: Create tables for foreclosure events and daily portfolio metrics

-- Foreclosure Events Table
CREATE TABLE IF NOT EXISTS foreclosure_events (
    id SERIAL PRIMARY KEY,
    upload_session_id UUID NOT NULL REFERENCES upload_sessions(id) ON DELETE CASCADE,
    file_date DATE,
    loan_id TEXT,
    investor_id TEXT,
    investor_loan_number TEXT,
    fc_atty_poc TEXT,
    fc_atty_poc_phone TEXT,
    fc_atty_poc_email TEXT,
    fc_jurisdiction TEXT,
    fc_status TEXT,
    active_fc_days INTEGER,
    hold_fc_days INTEGER,
    total_fc_days INTEGER,
    fc_closed_date DATE,
    fc_closed_reason TEXT,
    contested_start_date DATE,
    contested_reason TEXT,
    contested_summary TEXT,
    active_loss_mit TEXT,
    active_loss_mit_start_date DATE,
    active_loss_mit_reason TEXT,
    last_note_date DATE,
    last_note TEXT,
    title_received_actual_start DATE,
    title_received_expected_completion DATE,
    title_received_actual_completion DATE,
    title_received_delay_reason TEXT,
    first_legal_expected_start DATE,
    first_legal_actual_start DATE,
    first_legal_expected_completion DATE,
    first_legal_actual_completion DATE,
    first_legal_completion_variance INTEGER,
    first_legal_delay_reason TEXT,
    service_perfected_expected_start DATE,
    service_perfected_actual_start DATE,
    service_perfected_expected_completion DATE,
    service_perfected_actual_completion DATE,
    service_perfected_completion_variance INTEGER,
    service_perfected_delay_reason TEXT,
    publication_started_expected_start DATE,
    publication_started_actual_start DATE,
    publication_started_expected_completion DATE,
    publication_started_actual_completion DATE,
    publication_started_completion_variance INTEGER,
    publication_started_delay_reason TEXT,
    order_of_reference_expected_start DATE,
    order_of_reference_actual_start DATE,
    order_of_reference_expected_completion DATE,
    order_of_reference_actual_completion DATE,
    order_of_reference_completion_variance INTEGER,
    order_of_reference_delay_reason TEXT,
    judgment_entered_expected_start DATE,
    judgment_entered_actual_start DATE,
    judgment_entered_expected_completion DATE,
    judgment_entered_actual_completion DATE,
    judgment_entered_completion_variance INTEGER,
    judgment_entered_delay_reason TEXT,
    redemption_expires_expected_start DATE,
    redemption_expires_actual_start DATE,
    redemption_expires_expected_completion DATE,
    redemption_expires_actual_completion DATE,
    redemption_expires_completion_variance INTEGER,
    redemption_expires_delay_reason TEXT,
    sale_held_expected_start DATE,
    sale_held_expected_completion DATE,
    sale_held_actual_completion DATE,
    sale_held_completion_variance INTEGER,
    sale_held_delay_reason TEXT,
    rrc_expected_start DATE,
    rrc_actual_start DATE,
    rrc_expected_completion DATE,
    rrc_actual_completion DATE,
    rrc_completion_variance INTEGER,
    rrc_delay_reason TEXT,
    source_filename TEXT,
    data_issues JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Daily Portfolio Metrics Table
CREATE TABLE IF NOT EXISTS daily_metrics (
    id SERIAL PRIMARY KEY,
    upload_session_id UUID NOT NULL REFERENCES upload_sessions(id) ON DELETE CASCADE,
    loan_id TEXT,
    investor TEXT,
    investor_name TEXT,
    inv_loan TEXT,
    first_name TEXT,
    last_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    prin_bal NUMERIC(15, 2),
    unapplied_bal NUMERIC(15, 2),
    int_rate NUMERIC(8, 6),
    pi_pmt NUMERIC(10, 2),
    remg_term INTEGER,
    origination_date DATE,
    org_term INTEGER,
    org_amount NUMERIC(15, 2),
    lien_pos TEXT,
    next_pymt_due DATE,
    last_pymt_received DATE,
    first_pymt_due DATE,
    maturity_date DATE,
    loan_type TEXT,
    legal_status TEXT,
    warning TEXT,
    pymt_method TEXT,
    draft_day INTEGER,
    spoc TEXT,
    jan_25 NUMERIC(10, 2),
    feb_25 NUMERIC(10, 2),
    mar_25 NUMERIC(10, 2),
    apr_25 NUMERIC(10, 2),
    may_25 NUMERIC(10, 2),
    jun_25 NUMERIC(10, 2),
    jul_25 NUMERIC(10, 2),
    aug_25 NUMERIC(10, 2),
    sep_25 NUMERIC(10, 2),
    oct_25 NUMERIC(10, 2),
    nov_25 NUMERIC(10, 2),
    dec_25 NUMERIC(10, 2),
    source_filename TEXT,
    data_issues JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_foreclosure_events_upload_session_id ON foreclosure_events(upload_session_id);
CREATE INDEX IF NOT EXISTS idx_foreclosure_events_loan_id ON foreclosure_events(loan_id);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_upload_session_id ON daily_metrics(upload_session_id);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_loan_id ON daily_metrics(loan_id);