version: '3.8'
services:
  db:
    image: postgres:16
    container_name: nplvision_db
    restart: always
    environment:
      POSTGRES_DB: loanvision_db
      POSTGRES_USER: nplvision_user
      POSTGRES_PASSWORD: devonly_82928
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data